- .github/workflows/export-labels.yml
> Add label export file

- projects.yaml
Gradio lets you wrap any model, function or API with easy-to-use UIs. You can generate a link so anyone can run inference on a model. More info here: https://gradio.app
**Checklist:**
> Added Gradio

- projects.yaml
Visualize, create, and debug your image and video datasets and models with FiftyOne. Try the FiftyOne dataset and model zoo to bootstrap your Computer Vision project: https://github.com/voxel51/fiftyone
**Checklist:**
> Add project: FiftyOne

- projects.yaml
Added imodels, a python package which implements a variety of models for rule-based learning.
**Checklist:**
> add imodels

- projects.yaml
celer is originally a faster python/cython solver for sklearn.linear_model.Lasso. Now it supports more complex models which are not implemented in scikit-learn, such as the group lasso, the weighted lasso, the adaptive lasso, and more on logistic regression.
**Checklist:**
> Add project: celer

- projects.yaml
The project `caer` was added. Additionally, a new category `Computer/Machine Vision` was introduced in `projects.yaml`. 
Thank you!
**Checklist:**
> Add project "caer" @jasmcaus

- projects.yaml
Cornac is a comparative framework for multimodal recommender systems. It focuses on making it convenient to work with models leveraging auxiliary data (e.g., item descriptive text and image, social network, etc). Cornac enables fast experiments and straightforward implementations of new models. It is highly compatible with existing machine learning libraries (e.g., TensorFlow, PyTorch).
**Checklist:**
> Add project: Cornac

- projects.yaml
> Add project: PyFlink

- projects.yaml
Objax is an open source machine learning framework that accelerates research and learning thanks to a minimalist object-oriented design and a readable code base. Its name comes from the contraction of Object and JAX – a popular high-performance framework. Objax is designed by researchers for researchers with a focus on simplicity and understandability. Its users should be able to easily read, understand, extend, and modify it to fit their needs.
**Checklist:**
> Add Objax to the list of ML frameworks

- projects.yaml
- [x ] Add a project
Added pyRDF2Vec: a library to create embeddings for nodes in a knowledge graph
**Checklist:**
- [X ] I have read the [CONTRIBUTING](https://github.com/ml-tooling/best-of-ml-python/blob/main/CONTRIBUTING.md) guidelines.
- [ X] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.
> Add pyRDF2Vec to Graph category

- projects.yaml
Add openpyxl as suggested in #30. For now, I have not removed xlrd as it still is a popular project with 1.8k stars and the last commit activity in December 2020; hence, I would suggest to keep it in the list for now. Maybe a *deprecated* attribute or so for projects could make sense.
**Checklist:**
> Add openpxyl according to #30

- projects.yaml
> Add project: D-Tale

- projects.yaml
Populated the `conda_id:` property on the project, D-Tale.
**Checklist:**
> Add conda_id to D-Tale

- projects.yaml
Adding the `causalnex` package to projects.yaml.
**Checklist:**
> Add project: CausalNex

- projects.yaml
added bias-detector and data-describe
**Checklist:**
> Add projects: bias-detector and data-describe

- projects.yaml
**Checklist:**
- [x ] I have read the [CONTRIBUTING](https://github.com/ml-tooling/best-of-ml-python/blob/main/CONTRIBUTING.md) guidelines.
- [x ] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.
> add scikit-opt

- projects.yaml
- [ x] Add a project
Activeloop: An open-sourse project that is the fastest computer vision dataset management framework for data streaming, version-control and collaboration.
**Checklist:**
- [x ] I have read the [CONTRIBUTING](https://github.com/ml-tooling/best-of-ml-python/blob/main/CONTRIBUTING.md) guidelines.
- [x ] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.
> Add project: Activeloop

- projects.yaml
Adding whylogs as a project for data monitoring in data pipelines
WhyLogs collects approximate statistics and sketches of data on a column-basis into a statistical profile
**Checklist:**
> Adding whylogs

- projects.yaml
`KD-Lib`:  A PyTorch model compression library containing easy-to-use methods for knowledge distillation, pruning, and quantization.
**Checklist:**
> Add KD-Lib

- projects.yaml
Add a new framework to build a recommendation system base on Pytorch.
**Checklist:**
> Add project: Collie

- projects.yaml
Added MMOCR to the OCR section.
Project: https://github.com/open-mmlab/mmocr
MMOCR is an open-source toolbox based on PyTorch and mmdetection for text detection, text recognition, and the corresponding downstream tasks including key information extraction. It is part of the OpenMMLab project.
**Checklist:**
> Add project: MMOCR

- projects.yaml
> Add project: StatsForecast.

- projects.yaml
Closes https://github.com/ml-tooling/best-of-ml-python/issues/137
H2O-3: open source, in-memory, distributed, fast, and scalable machine learning and predictive analytics platform that allows you to build machine learning models on big data and provides easy productionalization of those models in an enterprise environment (core java package with python interface)
**Checklist:**
> Add project: H2O-3

- projects.yaml
A Neural Network based Time-Series model, inspired by [Facebook Prophet](https://github.com/facebook/prophet) and [AR-Net](https://github.com/ourownstory/AR-Net), built on PyTorch.
**Checklist:**
> Add project: NeuralProphet

- projects.yaml
see issue: https://github.com/ml-tooling/best-of-ml-python/issues/157
- Project Name: Population Shift Monitoring
- Github URL: [https://github.com/ing-bank/popmon](https://github.com/ing-bank/popmon)
- Category:  data-viz or others
- License: [MIT Licence](https://github.com/ing-bank/popmon/blob/master/LICENSE)
- Package Managers: pypi:popmon
**Additional context:**
popmon is a package that allows one to check the stability of a dataset. popmon works with both pandas and spark datasets.
**Checklist:**
> add popmon

- projects.yaml
A package for comprehensively validating your machine learning models and data with minimal effort.
**Checklist:**
> Add deepchecks

- projects.yaml
Plotly-Resampler: a plotly.py add-on that adds data downsampling (aggregating) functionality, enabling the visualization of large datasets.
**Checklist:**
> :sparkles: add plotly-resampler

- projects.yaml
> Add project: small-text

- projects.yaml
Geomstats: Geometry in Machine Learning
**Checklist:**
> Add project: Geomstats

- projects.yaml
the place for EDA of time series data
tslumen - EDA for time-series data
**Checklist:**
> Add tslumen

- projects.yaml
1. Update the AutoGluon project labels. AutoGluon no longer uses MXNet, but rather PyTorch for its backend. It also actively uses scikit-learn for various components.
2. Update the AutoGluon project github_id. AutoGluon has been migrated from awslabs/autogluon to autogluon/autogluon: https://github.com/autogluon/autogluon (https://github.com/awslabs/autogluon will redirect).
3. Add AutoGluon dockerhub_id : autogluon/autogluon (https://hub.docker.com/r/autogluon/autogluon)
4. Add AutoGluon docs_url : https://auto.gluon.ai
Source: I am a developer of AutoGluon ([commits](https://github.com/autogluon/autogluon/commits?author=Innixma))
Thanks for the awesome and informative repo!
**Checklist:**
> Update project: AutoGluon

- projects.yaml
> add pandas-ai

- projects.yaml
USearch implements Approximate Nearest Neighbors Search, similar to FAISS. Unlike FAISS and other HNSW implementations, however, it allows variable length vectors and User Defined Functions for distance metrics that are JIT-compiled in Python and forwarded to the C++ engine implementation.
**Checklist:**
> Add project: USearch

- projects.yaml
UForm is a library for Multi-Modal Fusion models, ideal for combined Vision-Language search tasks.
**Checklist:**
> Add project: UForm

- projects.yaml
EvaDB -- Database system for building simpler and faster AI-powered applications
**Checklist:**
> add evadb 

- projects.yaml
I'm the maintainer of litellm https://github.com/BerriAI/litellm - a simple & light package to call Bard, Anthropic, Cohere, Azure, OpenAI LLM Models
This PR adds support for models from all the above mentioned providers, in this pr I made a new adapter called litellm.py
Here's a sample of how it's used:
```
from litellm import completion
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"
messages = [{ "content": "Hello, how are you?","role": "user"}]
response = completion(model="gpt-3.5-turbo", messages=messages)
response = completion("command-nightly", messages)
response = completion(model="claude-instant-1", messages=messages)
```
**Checklist:**
> Add litellm - Update projects.yaml

- projects.yaml
Adding Determined, which is a platform that simplifies distributed training, hyperparameter tuning, experiment tracking, and resource management.
**Checklist:**
> Added Determined

- projects.yaml
> Add skforecast in time-series-data

- projects.yaml
This PR added CometML to projects list. CometML is an MLOps platform that supports experiment tracking, a model registry, model production management, and data lineage.
**Checklist:**
> Add project: CometML

- projects.yaml
Added NanoDL, a Jax-based library for building custom transformer models from scratch.
**Checklist:**
> Added NanoDL to projects.yaml

- projects.yaml
- [x ] Add a project
Runhouse - Apache 2.0 licensed open source project to be a universal runtime for ML jobs - use Runhouse to send and execute ML training/inference tasks written in regular Python on any infra (GPU / CPU), region, or cloud without the need for costly packaging or pipelining. Use Runhouse from local (IDE/notebook) for research, and call it from orchestrators in production. 
**Checklist:**
- [ x] I have read the [CONTRIBUTING](https://github.com/ml-tooling/best-of-ml-python/blob/main/CONTRIBUTING.md) guidelines.
- [ x] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.
> Add Runhouse to projects.yaml

- .github/workflows/update-best-of-list.yml
Thanks for the great list.
I've found that the updates have been failing for a while now. I think that it is the same as reported at https://github.com/best-of-lists/best-of/issues/216. I have confirmed that the fix is working on my fork https://github.com/not522/best-of-ml-python/actions/runs/10454068457.
**Checklist:**
> Update Actions Versions

- projects.yaml
> Add project: Opik

- projects.yaml
Add the [ridgeplot](https://github.com/tpvasconcelos/ridgeplot) project under the "Data Visualisation" category.
**Checklist:**
> Add project: ridgeplot

- projects.yaml
Add the pyclugen project, a Python implementation of the clugen algorithm for generating multidimensional clusters with arbitrary distributions described in <https://doi.org/10.1016/j.knosys.2023.110836>.
**Checklist:**
> Add project: pyclugen

- projects.yaml
Add project: effector
add project: effector.
effector is a python package that explains black box models that are trained on tabular data, using global and regional effect plots
**Checklist:**
-  I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.
> Add project: effector

- projects.yaml
Adding [skrub](https://github.com/skrub-data/skrub), a package that eases preprocessing and feature engineering for tabular machine learning. 
**Checklist:**
> Add project: skrub

- projects.yaml
- Coqui TTS has been forked and maintained by idiap organization. And it's available for latest Python version's.
**Checklist:**
> Update Coqui TTS project details in projects.yaml
